# Generated by Django 4.0.4 on 2022-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_date_created_post_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nluser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.tag'),
        ),
    ]
